mission09_annazlr/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission09_annazlr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_annazlr.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

mission09_annazlr/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission09_annazlr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_annazlr.Components
{
    //This is for showing the specified categories
    public class TypesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }
        public TypesViewComponent (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.Selected = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);


            return View(types);
        }
    }
}

mission09_annazlr/Views/Shared/BookSummary.cshtml
@{
}

@model Book

@* class = card makes the outline of the different boxes for each book. *@
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge bg-primary rounded-pill" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">
        <ul>
            <li>Author Name: @Model.Author</li>
            <li>Publisher Name: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification </li>
            <li>Category: @Model.Category</li>
            <li>Number of Pages: @Model.PageCount</li>
            <li>Price: $@Model.Price</li>
        </ul>

        @* Form to add a specific book to the cart *@
        <form method="post" asp-page="/Purchase">

            <input type="hidden" asp-for="@Model.BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm float-end">Add To Cart</button>
            </span>
        </form>
    </div>
</div>

mission09_annazlr/Views/Shared/_Layout.cshtml
@*Shared Layout for all pages*@

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BookStore</title>
    <link href="/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    @* Makes the black line along top with the Title on it *@
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BOOK STORE</div>
                <div class="col-6 text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    @* Give 3 columns for the "look at all these books part, and 9 for the book list *@
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            Look at all these books!
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>
@* This is a bootstrap address that I added in!  With Strong font for the title, and the abbreviation type *@
<footer>
    <address>
        <strong>Enterprise Development, Inc.</strong><br>
        W308 TRNB<br>
        Provo, UT 84602<br>
        <abbr title="Phone">P:</abbr> (801) 422-3884
    </address>
</footer>