mission09_annazlr/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using mission09_annazlr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_annazlr.Controllers
{
    public class PurchaseController : Controller
    {
        
        private IPurchaseRepository repo { get; set; }
        private Cart cart { get; set; }

        public PurchaseController (IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        public IActionResult Checkout()
        {
            return View(new ActualPurchase());
        }

        [HttpPost]
        public IActionResult Checkout(ActualPurchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.clearCart();

                return RedirectToPage("/Confirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

mission09_annazlr/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mission09_annazlr.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mission09_annazlr/Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission09_annazlr.Infrastructure;
using mission09_annazlr.Models;

namespace mission09_annazlr.Pages
{
    //Purchase Model for the Purchase page.
    public class PurchaseModel : PageModel
    {
        private IBookStoreRepository repo { get; set; }

        //Makes cart object of type cart
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }

        public PurchaseModel (IBookStoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        //OnGet request to get the cart.
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";

        }

        //Onpost request to add something to the cart cart
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostDelete(int bookId, string returnUrl)
        {
            cart.DeleteItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

    }
}

mission09_annazlr/Pages/Confirmation.cshtml
@page
@model mission09_annazlr.Pages.ConfirmationModel
@{
}
<div class="text-center">
    <h2>Thanks for your purchase! We hope you enjoy your books!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

mission09_annazlr/Pages/Purchase.cshtml
@page
@model mission09_annazlr.Pages.PurchaseModel
@{
}

@* Purchase Page *@
<h2>Your Cart</h2>

@* Makes purchase table *@
<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    @* Fills in table with info *@
    <tbody>
        @foreach(var i in Model.cart.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                @* This is for the delete button *@
                <td class="text-center">
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    @* Calculates the total *@
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table>

@* Continue shopping button *@
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-success" asp-controller="Purchase" asp-action="Checkout" >Checkout</a>
</div>

mission09_annazlr/Pages/_PurchaseLayout.cshtml
@* Purchase Layout similar to shared layout page, to keep consistency *@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">BOOK STORE</span>
    </div>

    <div class="row m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>